select * from information_schema.tables where table_schema = 'public';

CREATE TABLE employee 
(

	EMP_ID			INT PRIMARY KEY 
	,EMP_NAME		VARCHAR(50)	NOT NULL
	,DEPT_NAME		VARCHAR(50)	NOT NULL
	,SALARY			INT 
	, CONSTRAINT SALARY_CSTR CHECK(SALARY >= 0)
);

SELECT * FROM EMPLOYEE

INSERT INTO EMPLOYEE VALUES (101, 'Mohan', 'Admin', 4000);

INSERT INTO EMPLOYEE VALUES (102, 'Rajkumar', 'HR', 3000);
INSERT INTO EMPLOYEE VALUES (103, 'Akbar', 'IT', 4000);
INSERT INTO EMPLOYEE VALUES (104, 'Dorvin', 'Finance', 6500);
INSERT INTO EMPLOYEE VALUES (105, 'Rohit', 'HR', 3000);
INSERT INTO EMPLOYEE VALUES (106, 'Rajesh', 'Finance', 5000);
INSERT INTO EMPLOYEE VALUES (107, 'Preet', 'HR', 7000);

INSERT INTO EMPLOYEE VALUES (108, 'Maryam', 'Admin', 4000);
INSERT INTO EMPLOYEE VALUES (113, 'Gautham', 'Admin', 2000);

